language: python

python:
  - 3.6.8

services:
  - docker

before_script:
  - pip install docker-compose
  - echo VK_TOKEN >> cfg
  - echo PG_PASS >> cfg
  - git clone https://github.com/LeadNess/go-vk-news-loader.git

script:
  - ./deploy/deploy_service < cfg
